/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ca.uvic.seng330.ex4;

public class App {
  private static final App INSTANCE = new App();
  private static String className = "App";
  private static final String ERROR_MESSAGE = "[There is already an instance of " + className + "  running]";

  private App() {}

  public static void main(String[] args) {
    System.out.println(getInstance().getGreeting());
    Driver.GeneratedDataPopulate();
  }

  public static App getInstance() {
    return INSTANCE;
  }

  public String getGreeting() {
    return "Running Tests on Whale Tracking System";
  }
}
